import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="top-bar">
          <div className="logo">loopstudios</div>
          <div style={{ height: "100%", maxWidth: 20 }}>
            <Image
              className="hamburger"
              height={20}
              width={20}
              layout="fixed"
              priority
              src="/icon-hamburger.svg"
            />
          </div>
        </div>
        <nav className="mobile-nav">
          <img src="images/icon-close.svg" alt="close navigation trigger" />
          <ul className="mobile-list">
            <li className="mobile-item">
              <a href="#" className="mobile-link">
                About
              </a>
            </li>
            <li className="mobile-item">
              <a href="#" className="mobile-link">
                Careers
              </a>
            </li>
            <li className="mobile-item">
              <a href="#" className="mobile-link">
                Events
              </a>
            </li>
            <li className="mobile-item">
              <a href="#" className="mobile-link">
                Products
              </a>
            </li>
            <li className="mobile-item">
              <a href="#" className="mobile-link">
                Support
              </a>
            </li>
          </ul>
        </nav>
      </header>
      <section className="hero">
        <div className="hero__content">
          <h1>Immersive experiences that Deliver</h1>
        </div>
      </section>
      <main>
        <section className="interactive-vr">
          <picture>
            <source
              srcset="images/desktop/image-interactive.jpg"
              media="(min-width: 800px)"
            />
            <source srcset="images/mobile/image-interactive.jpg" />
            <img src="images/desktop/image-interactive.jpg" alt="" />
          </picture>
          <h2>The Leader in Interactive VR</h2>
          <p>
            Founded in 2011, Loopstudios has been producing world-class virtual
            reality projects for some of the best companies around the globe.
            Our award-winning creations have transformed businesses through
            digital experiences that bind to their brand.
          </p>
        </section>
        <section className="our-creations">
          <h2>Our Creations</h2>
          <picture className="creation deep-earth">
            <source
              srcset="images/desktop/image-deep-earth.jpg"
              media="(min-width: 800px)"
            />
            <source srcset="images/mobile/image-deep-earth.jpg" />
            <img src="images/desktop/image-deep-earth.jpg" alt="" />
          </picture>
          <picture className="creation night-arcade">
            <source
              srcset="images/desktop/image-night-arcade.jpg"
              media="(min-width: 800px)"
            />
            <source srcset="images/mobile/image-night-arcade.jpg" />
            <img src="images/desktop/image-night-arcade.jpg" alt="" />
          </picture>
        </section>
      </main>
      <footer>
        <div className="logo">loopstudios</div>
        <ul className="pages-list">
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              About
            </a>
          </li>
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              Careers
            </a>
          </li>
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              Events
            </a>
          </li>
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              Products
            </a>
          </li>
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              Support
            </a>
          </li>
        </ul>
        <ul className="social-list">
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              About
            </a>
          </li>
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              Careers
            </a>
          </li>
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              Events
            </a>
          </li>
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              Products
            </a>
          </li>
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              Support
            </a>
          </li>
        </ul>
        <div className="copyright">2021 Loopstudios. All rights reserved</div>
      </footer>
    </div>
  );
}
