import NavigationBar from "components/NavigationBar/NavigationBar";
import Head from "next/head";
import Image from "next/image";
import { useInView } from "react-intersection-observer";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const { ref: heroObserverRef, entry } = useInView({
    threshold: 0.75,
    rootMargin: "0px 0px 0px 0px",
    initialInView: true,
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavigationBar inView={!entry?.isIntersecting}>
          <a href="#">About</a>
          <a href="#">Careers</a>
          <a href="#">Events</a>
          <a href="#">Products</a>
          <a href="#">Support</a>
        </NavigationBar>
      </header>
      <section className="hero" ref={heroObserverRef}>
        <Image
          src="/desktop/image-hero.jpg"
          layout="fill"
          objectFit="cover"
          objectPosition="50%"
          className="hero__img"
          quality={80}
        />
        <div className="hero__content">
          <h1>Immersive experiences that Deliver</h1>
        </div>
      </section>
      <main>
        <section className="interactive-vr">
          <Image
            src="/desktop/image-interactive.jpg"
            layout="responsive"
            width="731"
            height="500"
          />
          <div className="content">
            <h2>The Leader in Interactive VR</h2>
            <p>
              Founded in 2011, Loopstudios has been producing world-class
              virtual reality projects for some of the best companies around the
              globe. Our award-winning creations have transformed businesses
              through digital experiences that bind to their brand.
            </p>
          </div>
        </section>

        <section className="our-creations">
          <h2>Our Creations</h2>
          <div className="creation-card">
            <h3 className="title">Deep Earth</h3>
            <div className="img-wrapper">
              <Image
                src="/desktop/image-deep-earth.jpg"
                layout="fill"
                objectFit="cover"
                quality={90}
                objectPosition={"100% 75%"}
                className="image"
              />
            </div>
          </div>
          <div className="creation-card">
            <h3 className="title">Night Arcade</h3>
            <div className="img-wrapper">
              <Image
                src="/desktop/image-night-arcade.jpg"
                layout="fill"
                objectFit="cover"
                quality={90}
                className="image"
              />
            </div>
          </div>
          <button className="outlined-button">See All</button>
        </section>
      </main>
      <footer>
        <div className="logo">loopstudios</div>
        <ul className="pages-list">
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              About
            </a>
          </li>
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              Careers
            </a>
          </li>
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              Events
            </a>
          </li>
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              Products
            </a>
          </li>
          <li className="pages-list__item">
            <a href="#" className="pages-list__link">
              Support
            </a>
          </li>
        </ul>
        <ul className="social-list">
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              About
            </a>
          </li>
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              Careers
            </a>
          </li>
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              Events
            </a>
          </li>
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              Products
            </a>
          </li>
          <li className="social-list__item">
            <a href="#" className="social-list__link">
              Support
            </a>
          </li>
        </ul>
        <div className="copyright">2021 Loopstudios. All rights reserved</div>
      </footer>
    </div>
  );
}
